[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm add -D tsup typescript", "cd node_modules/x402 && npx tsup"]

[start]
cmd = "pnpm start"
